### ISSUE TITLE
Sequelize-ibmi performance issue

### ISSUE THREAD

**Issue by HaithamRashad** [markdirish/sequelize-ibmi#3]
Hi, 

I want your support to solve performance issue of sequelize-ibmi using ODBC connection. 

The situation is as following:
I have a nodejs application which uses sequelize-ibmi to connect to IBM i database through ODBC, but the application is very slow comparing with the same application which uses the ordinary sequelize to connect to sql database.

Is there any recommendations to solve this slowness when connecting to IBM i database through ODBC and sequelize-ibmi ?

**Comment by markdirish** [comment]
It is really hard to diagnose the problem without more information. 

* What sorts of queries are you doing?
* What performance do you see running those same queries using the `odbc` package by itself (this is the connector that `sequelize-ibmi` uses)
* What does your connection string / DSN look like?
* What DBMS are you comparing it to (MySQL, Postgres, etc)? And are you running those locally when connecting, as opposed to a remote `ibmi` system?

**Comment by mdgozza** [comment]
Something similar has also been reported to me, that the ODBC ibmi connection ( regardless of sequelize ) is somewhat slower than the ibm_db module. 

I can run some tests to help compare contrast the two if there is a specific test you'd like to see.

I'll try to get some numbers and write back either way 👍

**Comment by HaithamRashad** [comment]
Q: What sorts of queries are you doing?
A: Very simple queries: selecting from tables using sequelize models.
- ------------------------------------------------------------------------------
Q: What performance do you see running those same queries using the odbc package by itself (this is the connector that 
     sequelize-ibmi uses)
A: I don't know how to run queries using the odbc package by itself, I'll search for it and see.
-------------------------------------------------------------------------------
Q: What does your connection string / DSN look like?
A: DSN=connectionName;UID=userID;PWD=Password
-------------------------------------------------------------------------------
Q: What DBMS are you comparing it to (MySQL, Postgres, etc)? And are you running those locally when connecting, as opposed 
     to a remote ibmi system?
A: I'm comparing with MS SQL server, the same network environment is used for both.

I wish you got the required information to be able to diagnose the problem.

**Comment by HaithamRashad** [comment]
Can we use OLEDB connection instead of ODBC connection?
