### ISSUE TITLE
Problem ODBC Driver Manager

### ISSUE THREAD

**Issue by MarioAquino-MAQU** [markdirish/sequelize-ibmi#5]
Hello,

Thank you for this package, I have created several node.js applications using Sequelize before. And I'm thrilled that there is also a package for DB2 on the IBMi!!

I have a problem connecting to the database. Below you will find my Sequelize instantiation:

```
const Sequelize = require('sequelize-ibmi');
let sequelize = new Sequelize(process.env.DB_DATABASE, process.env.DB_USERNAME, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: 'ibmi',
    protocol: 'TCP/IP',
    operatorsAliases: 0,
    pool: {
        max: 20,
        min: 5,
        acquire: 30000,
        idle: 10000
    }
});

sequelize.options.define.freezeTableName = true;
sequelize.options.define.underscored = true;
sequelize.options.define.underscoredAll = true;
module.exports.connection = sequelize;
```

Whenever I try to read something from this collection I get this response (and a 500 error serverside):

```
{
    "odbcErrors": [
        {
            "state": "01S00",
            "code": 0,
            "message": "[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified"
        },
        {
            "state": "01S00",
            "code": 0,
            "message": "[Microsoft][ODBC Driver Manager] Invalid connection string attribute"
        }
    ]
}
```

Which Drivername does the package expect? Here a list of the IBM drivers I have installed on my pc:
![image](https://user-images.githubusercontent.com/28532500/143226337-605152e6-49e8-4757-a308-324fadaa72cd.png)

I think the I have the right drivers installed on my pc, but maybe the name does not correspond to what the package expects. Or maybe it is a problem in my instantiation?

Thank you for your response!

**Comment by MarioAquino-MAQU** [comment]
@markdirish can you have a look when you find the time? I feel like I have the right driver but with the wrong name...

**Comment by markdirish** [comment]
Hi @MarioAquino-MAQU ,

I think the issue may be the way you are initializing the `sequelize` object. I didn't write good documentation, but this dialect expects the option `odbcConnectionString` to be passed in, with the proper format. Connection string options can be found at: https://www.ibm.com/docs/en/i/7.4?topic=details-connection-string-keywords. I imagine your initialization should look something like:

```
const Sequelize = require('sequelize-ibmi');
let sequelize = new Sequelize({
  odbcConnectionString: `DRIVER=IBM i Access ODBC Driver;UID=${process.env.DB_USERNAME};PWD=${process.env.DB_PASSWORD};`,
  datanase: process.env.DB_DATABASE,
  dialect: 'ibmi',
  operatorsAliases: 0,
  pool: {
      max: 20,
      min: 5,
      acquire: 30000,
      idle: 10000
  }
});
```

Give that a shot and let me know what happens

**Comment by MarioAquino-MAQU** [comment]
Hi @markdirish ,

Thank you for your reaction! It has been really useful. Here the new version of my connection-class (can be useful for someone reading this later):

```
const Sequelize = require('sequelize-ibmi');
// https://sequelize.org/v3/api/sequelize/
let sequelize = new Sequelize({
    odbcConnectionString: `DRIVER=IBM i Access ODBC Driver;UID=${process.env.DB_USERNAME};PWD=${process.env.DB_PASSWORD};
    SYSTEM=${process.env.DB_HOST};DBQ=${process.env.DB_SCHEMA};`,
    database: process.env.DB_DATABASE,
    dialect: 'ibmi',
    protocol: 'TCP/IP',
    operatorsAliases: 0,
    pool: {
        max: 20,
        min: 5,
        acquire: 30000,
        idle: 10000
    }
});

sequelize.options.define.freezeTableName = true;
sequelize.options.define.underscored = true;
sequelize.options.define.underscoredAll = true;

module.exports.connection = sequelize;
```
I'm able to connect to my DB2 database but encountered another problem which I can't solve. (Sorry about that)

Here the code for my GET request:
```
router.route('/')
    .get((req, res) => {
        User.findAll()
            .then((users) => {
                res.status(200).send(users);
            }).catch((err) => {
                res.status(500).send(err);
            });
    })
```
The error returned: **[IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0206 - Column or global variable email not found.**

In my console I see this output:
```
Server started on port 3000
Executing (default): SELECT "id", "firstname", "lastname", "email" FROM "USERS" AS "USERS"
GET /api/users 500 1382.733 ms - 143
```

Pretty sure the problem is caused by the double quotes in the select-statement. This is supposed to be without quotations?
I'm sure you have encountered this before. Am I missing some sort of config?

**Comment by markdirish** [comment]
How is the table defined? Was it defined with sequelize, or is this a table that you previously created? I suspect the issue is with delimited vs. non-delimited identifiers: https://www.ibm.com/docs/en/i/7.4?topic=identifiers-sql

Sequelize will make identifiers delimited with double quotes, like `"email"`, but if you defined the table to have field `email` (without double-quotes), you will have to define it in sequelize as `"EMAIL"`, as non-delimited identifiers are converted to uppercase.

**Comment by MarioAquino-MAQU** [comment]
Thank you for your response!

The table is created using migrations (I think from a Laravel PHP project [https://github.com/cooperl22/laravel-db2](https://github.com/cooperl22/laravel-db2)). The column names are defined in uppercase as you assumed. 
![image](https://user-images.githubusercontent.com/28532500/144640012-62095fcf-ea39-40f5-b04f-87417bb6e40b.png)

Before creating this ticket I have put the keys in uppercase in my sequelize-model but this does not seem to solve it. Sequelize converts EMAIL to e_m_a_i_l in the query.
```
const connection = require('./sequelize-connection').connection;
const Sequelize = require('sequelize');

const User = connection.define('USERS', {
    // Model attributes are defined here
    ID: {
        type: Sequelize.INTEGER,
        primaryKey: true,
    },
    FIRSTNAME: Sequelize.STRING,
    LASTNAME: Sequelize.STRING,
    EMAIL: Sequelize.STRING
    }, {
    // Other model options go here
    sequelize: connection, // We need to pass the connection instance
    modelName: 'users', // We need to choose the model name
    timestamps: false,
});

module.exports = User;
```
```
GET /api/users 500 2004.702 ms - 221
Executing (default): SELECT "i_d" AS "ID", "f_i_r_s_t_n_a_m_e" AS "FIRSTNAME", "l_a_s_t_n_a_m_e" AS "LASTNAME", "e_m_a_i_l" AS "EMAIL" FROM "USERS" AS "USERS"
```
